default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: paulo
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  database: rails_production
